export const DATA_FETCHED = 'DATA_FETCHED';
export const DATA_SUCCEEDED = 'DATA_SUCCEEDED';
export const DATA_FAILED = 'DATA_FAILED';
export const TITLE_CHANGED = 'TITLE_CHANGED';

export const CONTENT_REFRESH = 'CONTENT_REFRESH';
export const CONTENT_UPDATED = 'CONTENT_UPDATED';
export const CONTENT_UPDATE_VALUE = 'CONTENT_UPDATE_VALUE';
export const CONTENT_SAVE = 'CONTENT_SAVE';

export const APP_SHOW_DRAWER = 'APP_SHOW_DRAWER';
